### ISSUE TITLE
FR: Grafana variables

### ISSUE THREAD

**Issue by d4nnyx** [computestdev/grafana-cloudwatchalarm-datasource#5]
Hi, it seems that the datasource does not support passing Grafana variables, which is an issue when trying to create dynamical dashboard. Could you please confirm it and add the support, please?

![Screenshot 2023-09-18 at 20 19 13](https://github.com/computestdev/grafana-cloudwatchalarm-datasource/assets/24275013/857e8d4e-9397-4fa0-b65d-73f0b3fe6ca3)

**Comment by d4nnyx** [comment]
Are you planning to release a new version?

**Comment by ghost** [comment]
Yes, tomorrow. But it also might take a bit of time, because grafana has to review the new release.

**Comment by ghost** [comment]
v1.2.0 has been deployed to the grafana plugin platform
