### ISSUE TITLE
Invalid payload for AlarmTypes

### ISSUE THREAD

**Issue by bgardner-noggin** [computestdev/grafana-cloudwatchalarm-datasource#6]
Invalid payload for AlarmTypes

Version 1.1.0 sends the following payload to my endpoint

{
  Action: 'DescribeAlarms',
  AlarmNamePrefix: 'BAR',
  AlarmTypes: [ { undefined: 'MetricAlarm' }, { undefined: 'CompositeAlarm' } ],
  StateValue: 'ALARM',
  Version: '2010-08-01'
}

AlarmTypes is meant to be an array eg

  AlarmTypes: [ 'MetricAlarm', 'CompositeAlarm' ],

**Comment by ghost** [comment]
How are you testing this? If I dump the data that I am sending to the AWS SDK:

```go
plog.Warn(fmt.Sprintf("cloudwatchApi.DescribeAlarms: %+v\n", &alarmsParams))
alarmsResponse, err := cloudwatchApi.DescribeAlarms(&alarmsParams)
...
```

I end up with:
```
logger=plugin.computest-cloudwatchalarm-datasource t=2023-09-21T15:52:52.023536187Z level=warn msg="cloudwatchApi.DescribeAlarms: {\n  AlarmTypes: [\"MetricAlarm\",\"CompositeAlarm\"],\n  StateValue: \"ALARM\"\n}\n"
```
Which looks okay to me.

If I override the endpoint to my own server (which simply dumps the request url and body), I end up with:

```
POST /
Action=DescribeAlarms&AlarmTypes.member.1=MetricAlarm&AlarmTypes.member.2=CompositeAlarm&StateValue=ALARM&Version=2010-08-01
```
Which also looks okay to me

**Comment by bgardner-noggin** [comment]
Ahh, it must be my proxy which is transforming the arguments correctly. I thought my proxy was logging the raw arguments, but is is logging the transformed arguments.
